"""Add assigned_branches to AllowedEmail

Revision ID: 639d6ca71cd3
Revises: 
Create Date: 2025-06-11 20:09:43.349990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639d6ca71cd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
